name: scheduled-backfill

on:
  schedule:
    - cron: '0 * * * *'   # cada hora, ajústalo si quieres (UTC)
  workflow_dispatch:      # permite lanzar manualmente desde GitHub UI

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run incremental backfill
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Ajusta el comando según tu script (ejecuta solo incremental)
          python init_and_backfill.py --incremental --interval 1h
